# Site settings
title: Jakub Tucholski
# email: jtucholski00@gmail.com
description: >
  Personal site of Jakub Tucholski. 
baseurl: ""
url: "http://jakubtuchol.github.io" 
twitter_username: jakubtuchol
github_username:  jakubtuchol

# Build settings
markdown: kramdown
